### ISSUE TITLE
Timings of frames

### ISSUE THREAD

**Issue by anandijain** [kimikage/ProfileSVG.jl#59]
Currently, I don't see any options to see how long the program spent in a given frame/block.

Ideally I wouldn't have to run the profiler then run my `f` again with `@time`. 

I think it'd be pretty useful to also have stats on this in the SVG, is this possible? 

Thanks!

**Comment by kimikage** [comment]
Since the timer used for profiling is not highly accurate, it is difficult to indicate the exact duration.
There are several possible options.
1. Display only the count number
2. Support the conversion to physical time, knowing that it is inaccurate
3. Allow manual correction of the conversion factor
4. Add a calibration mechanism

Let's support up to 2. first, shall we?

**Comment by anandijain** [comment]
thanks for quick response. that sounds great. 

i figured it had something to do with not being able to pin down an accurate result.

any way i can help?
